[package]
name = "hello_lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.7.3"
serde = "1.0.156"
serde_json = "1.0.94"
tokio = "1.26.0"
