version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-rust"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-umzh034xr5c3"
s3_prefix = "hello-rust"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
